"""add_card_enhancements_and_card_members

Revision ID: 9f02b4762492
Revises: 46146299e0fd
Create Date: 2026-02-02 11:46:00.480021

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f02b4762492'
down_revision: Union[str, Sequence[str], None] = '46146299e0fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('card_members',
    sa.Column('card_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['card_id'], ['todos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('card_id', 'user_id')
    )
    op.add_column('todos', sa.Column('position', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('todos', sa.Column('due_date', sa.DateTime(timezone=True), nullable=True))
    op.add_column('todos', sa.Column('list_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'todos', 'lists', ['list_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'todos', type_='foreignkey')
    op.drop_column('todos', 'list_id')
    op.drop_column('todos', 'due_date')
    op.drop_column('todos', 'position')
    op.drop_table('card_members')
    # ### end Alembic commands ###
